name: Sync To Gitee
description: 每天凌晨 02:30 自动同步所有仓库至 Gitee, 不包括本仓库.

on:
  workflow_dispatch:
  schedule:
    - cron: '30 18 * * *'

jobs:
  run:
    name: Sync Job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v1
      
    - name: Generate repo list
      id: repo
      uses: yi-Xu-0100/repo-list-generator@v1.0.0

    - name: Echo repo list
      run: echo '${{ steps.repo.outputs.repoList }}'

    - name: Mirror Github to Gitee with white list
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/susususutie
        dst: gitee/susususutie
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        static_list: '${{ steps.repo.outputs.repoList }}'
        account_type: user
        black_list: 'sync-to-gitee'
        force_update: true
        debug: true
