# version: 1。1.0
# author: [yiXu](https://github.com/yi-Xu-0100)
# guide: [yi-Xu-0100/hub-mirror](https://github.com/yi-Xu-0100/hub-mirror)
# template: [sync2gitee.list.yml](https://github.com/yi-Xu-0100/hub-mirror/blob/main/template/sync2gitee.list.yml)
# lastmod: 2021-02-02 10:23:02

name: Sync All Repo To Gitee
on:
  workflow_dispatch:
  schedule:
    - cron: '30 18 * * *'
jobs:
  run:
    name: Sync All GitHub Repos to Gitee
    runs-on: ubuntu-latest
    steps:

      - name: 获取仓库名与时间
        id: info
        uses: actions/github-script@v3.1
        with:
          result-encoding: string
          script: |
            core.setOutput('time', new Date(Date.now()).toISOString().replace(/[^0-9]/g, ""));
            core.setOutput('key', `${context.repo.owner}-${context.repo.repo}`);

      - name: 缓存仓库数据
        uses: actions/cache@v2.1.3
        id: cache
        with:
          path: ${{ github.workspace }}/hub-mirror-cache
          key: ${{ runner.os }}-${{ steps.info.outputs.key }}-list-cache-${{ steps.info.outputs.time }}
          restore-keys: ${{ runner.os }}-${{ steps.info.outputs.key }}-list-

      - name: 生成仓库列表(仅非fork且非private的仓库)
        id: repo
        uses: yi-Xu-0100/repo-list-generator@v1.0.1

      - name: 打印仓库名
        run: "echo '${{ steps.repo.outputs.repoList }}'"

      - name: 同步仓库
        uses: Yikun/hub-mirror-action@v0.13
        with:
          src: github/susususutie
          dst: gitee/susususutie
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: '${{ steps.repo.outputs.repoList }}'
          black_list: 'sync-to-gitee'
          cache_path: /github/workspace/hub-mirror-cache
          account_type: user
          force_update: true
          debug: true

      - name: 打印缓存数据
        run: |
          ls -la ${{ github.workspace }}/hub-mirror-cache
